spring.application.name=MediaConverter
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB
app.input.path=${INPUT_PATH:.tmp/uploads/}
app.output.path=${OUTPUT_PATH:./videos_convertidos/}