spring.application.name=MediaConverter

spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

# URL de conexão apontando para o localhost
spring.datasource.url=jdbc:postgresql://localhost:5432/db_conversor
spring.datasource.username=arthur
spring.datasource.password=senhafodona
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create-drop


# Mostra no console os comandos SQL que o Spring gerar
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

api.security.token.secret=${TOKEN_SECRET:chave_padrao_para_testes_locais}
app.ffmpeg.path=${FFMPEG_PATH:ffmpeg}

# Configurações de envio de e-mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL-USERNAME}
spring.mail.password=${EMAIL-PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


